---
title: "DEG coordinates"
author: "Samuel Gurr"
date: "September, 6, 2023"
output: html_document
---

## Setup: 

```{r setup, include=TRUE}

knitr::opts_knit$set(root.dir = "C:/Users/samjg/Documents/Github_repositories/EAD-ASEB-Airradians_Popgen_OA/RAnalysis")

```

### Load libraries:

```{r load_libraries, include = TRUE}
# load libraries - notes show the install command needed to install (pre installed)
library(tidyverse)
library(ape)
library(plotgardener) # BiocManager::install("plotgardener")
# BiocManager::install("rnaseqGene")
```

### Set path:

```{r set the path out, include = TRUE}
path_out = 'C:/Users/samjg/Documents/Github_repositories/EAD-ASEB-Airradians_Popgen_OA/RAnalysis/Output/Transcriptomics/DESeq2'
```

### Load data:

```{r load gff, include = TRUE}

## gff file
Airradians_gff <- read.gff("../../../Bioinformatics/refs/Airradians/GCF_041381155.1_genomic.gff") %>% 
                    dplyr::filter(type %in% c('region','mRNA')) %>%
                    dplyr::mutate(transcript_id = 
                                    case_when(type %in% 'mRNA' ~
                                                            gsub('.*ID=',
                                                                 '',
                                                                 (gsub(';Parent.*','',attributes))
                                                                 ),
                                              TRUE ~ NA)) %>% 
                    dplyr::select(!c(score, strand, phase)) %>% 
                    dplyr::mutate(chromosome = case_when(seqid %in% 'NC_091134.1' ~ 'CM084264.1',
                                            seqid %in% 'NC_091135.1' ~ 'CM084265.1',
                                            seqid %in% 'NC_091136.1' ~ 'CM084266.1',
                                            seqid %in% 'NC_091137.1' ~ 'CM084267.1',
                                            seqid %in% 'NC_091138.1' ~ 'CM084268.1',
                                            seqid %in% 'NC_091139.1' ~ 'CM084269.1',
                                            seqid %in% 'NC_091140.1' ~ 'CM084270.1',
                                            seqid %in% 'NC_091141.1' ~ 'CM084271.1',
                                            seqid %in% 'NC_091142.1' ~ 'CM084272.1',
                                            seqid %in% 'NC_091143.1' ~ 'CM084273.1',
                                            seqid %in% 'NC_091144.1' ~ 'CM084274.1',
                                            seqid %in% 'NC_091145.1' ~ 'CM084275.1',
                                            seqid %in% 'NC_091146.1' ~ 'CM084276.1',
                                            seqid %in% 'NC_091147.1' ~ 'CM084277.1',
                                            seqid %in% 'NC_091148.1' ~ 'CM084278.1',
                                            seqid %in% 'NC_091149.1' ~ 'CM084279.1'),
                                  chromosome_num =   case_when(
                                            chromosome %in% 'CM084264.1' ~ 1,
                                            chromosome %in% 'CM084265.1' ~ 2,
                                            chromosome %in% 'CM084266.1' ~ 3,
                                            chromosome %in% 'CM084267.1' ~ 4,
                                            chromosome %in% 'CM084268.1' ~ 5,
                                            chromosome %in% 'CM084269.1' ~ 6,
                                            chromosome %in% 'CM084270.1' ~ 7,
                                            chromosome %in% 'CM084271.1' ~ 8,
                                            chromosome %in% 'CM084272.1' ~ 9,
                                            chromosome %in% 'CM084273.1' ~ 10,
                                            chromosome %in% 'CM084274.1' ~ 11,
                                            chromosome %in% 'CM084275.1' ~ 12,
                                            chromosome %in% 'CM084276.1' ~ 13,
                                            chromosome %in% 'CM084277.1' ~ 14,
                                            chromosome %in% 'CM084278.1' ~ 15,
                                            chromosome %in% 'CM084279.1' ~ 16)) %>% 
                  dplyr::select(transcript_id, chromosome, chromosome_num, start, end, type)



Airradians_chrom_bpcumul <- Airradians_gff %>%  
                                    dplyr::select(chromosome, chromosome_num, start, end, type) %>%  
                                    dplyr::filter(type %in% 'region') %>% 
                                    na.omit() %>% 
                                    dplyr::mutate(bp_cumulative = cumsum(end) ) %>% 
                                    dplyr::select(chromosome_num, bp_cumulative)


Airradians_gff_bpcumul <- merge(Airradians_chrom_bpcumul, Airradians_gff)
View(Airradians_gff_bpcumul)
```

### Load DESEq2 results for F1 nad F2:

```{r load DESeq2 results DEGs}

# load the F1 DEGs
F1_DESeq2_results  <- read.csv(file="Output/Transcriptomics/DESeq2/F1_juveniles/F1_DESeq2results_F1s.csv", header=T) %>% 
                        dplyr::select(Airradians_TranscriptID, padj,log2FoldChange) %>% 
                        dplyr::rename(transcript_id = Airradians_TranscriptID) %>% 
                        dplyr::filter(padj < 0.05) %>% 
                        dplyr::mutate(direction = 
                                        case_when(log2FoldChange > 0 ~ 'up',
                                                  log2FoldChange < 0 ~ 'down')
                                      )
nrow(F1_DESeq2_results) # 133


# load the F2 DEGs
F2_DESeq2_results  <- read.csv(file="Output/Transcriptomics/DESeq2/F2_juveniles/F2_DESeq2results_F2s.csv", header=T) %>% 
                        dplyr::select(Airradians_TranscriptID, padj,log2FoldChange) %>% 
                        dplyr::rename(transcript_id = Airradians_TranscriptID) %>% 
                        dplyr::filter(padj < 0.05) %>% 
                        dplyr::mutate(direction = 
                                        case_when(log2FoldChange > 0 ~ 'up',
                                                  log2FoldChange < 0 ~ 'down')
                                      )
nrow(F2_DESeq2_results) # 21

```
### Merge the gff annotation of chromosome number start and end with the DEGs
```{r merge and save csv}

F1_DESeq2_results_coordinates <- merge(Airradians_gff_bpcumul, F1_DESeq2_results, by = 'transcript_id') %>% dplyr::mutate(Gen = 'F1')
F2_DESeq2_results_coordinates <- merge(Airradians_gff_bpcumul, F2_DESeq2_results, by = 'transcript_id') %>% dplyr::mutate(Gen = 'F2')

# write csv files out
write.csv(F1_DESeq2_results_coordinates, "Output/Transcriptomics/DESeq2/F1_juveniles/F1_DESeq2results_coordinates.csv")
write.csv(F2_DESeq2_results_coordinates, "Output/Transcriptomics/DESeq2/F2_juveniles/F2_DESeq2results_coordinates.csv")
```
* try some figures, manhattan, pie segment, etc.
```{r}

axis_set$chromosome_num
axis_set <- F1_DESeq2_results_coordinates |>
  group_by(chromosome_num) |>
  summarize(center = mean(bp_cumulative))

ylim <- F1_DESeq2_results_coordinates |>
  filter(log2FoldChange == min(log2FoldChange)) |>
  mutate(ylim = abs(floor(log2FoldChange)) + 2) |>
  pull(ylim)

All_DEGs <- rbind(F1_DESeq2_results_coordinates,
                  F2_DESeq2_results_coordinates)
manhplot <- ggplot(All_DEGs, 
                   aes(
                    x = (start + bp_cumulative), y = abs(as.numeric(log2FoldChange)),
                    color = as_factor(chromosome_num), shape = Gen, size = log10(padj)
                  )) +
                    # geom_hline(
                    #   yintercept = log2FoldChange, color = "grey40",
                    #   linetype = "dashed"
                    # ) +
                    geom_point(alpha = 0.75) +
                    scale_x_continuous(
                      label = axis_set$chromosome_num,
                      breaks = axis_set$center
                    ) +
                    scale_color_manual(values = 
                                          rep(c("#276FBF", "#183059"),
                    unique(length(axis_set$chromosome_num))
                    )) + 
                    theme_bw() +
                    facet_wrap(~Gen*direction)# +
                    # scale_y_continuous(expand = c(0, 0), limits = c(0, ylim)) +
                    # scale_color_manual(values = rep(
                    #   c("#276FBF", "#183059"),
                    #   unique(length(axis_set$chr))
                    # )) +
                    # scale_size_continuous(range = c(0.5, 3)) +
                    # labs(
                    #   x = NULL,
                    #   y = "-log<sub>10</sub>(p)"
                    # ) +
                    # theme_minimal() +
                    # theme(
                    #   legend.position = "none",
                    #   panel.grid.major.x = element_blank(),
                    #   panel.grid.minor.x = element_blank(),
                    #   axis.title.y = element_markdown(),
                    #   axis.text.x = element_text(angle = 60, size = 8, vjust = 0.5)
                    # )


ggplot( (All_DEGs %>% group_by(chromosome_num, Gen) %>% summarise(n = n())), 
       aes(x = "", y = n, fill = as.character(chromosome_num))) + 
  geom_bar(stat = "identity", 
           width = 1, 
           position = position_fill()) +
  scale_fill_brewer(palette="BrBG") +
  theme_classic() +
  coord_polar(theta = "y") + 
  facet_wrap( ~ Gen)

# set of 20 random colors
library(randomcoloR)
library(geomtextpath)

colors <- distinctColorPalette(20)
df_F1 <- (All_DEGs %>% filter(Gen %in% 'F1') %>% 
            group_by(chromosome_num, Gen) %>% 
            summarise(n = n())) %>% 
            mutate(chromosome_num=fct_relevel(as.factor(chromosome_num),c('1','2','3','4',
                                                               '5','6','7','8',
                                                               '9','10','11','12',
                                                               '13','14','15','16')))

df_F1$chromosome_num
df_F2 <- (All_DEGs %>% filter(Gen %in% 'F2') %>% group_by(chromosome_num, Gen) %>% summarise(n = n()))
Pie_F1 <- ggplot(df_F1, aes(x = 1, y = n, fill = as.character(chromosome_num))) +
              geom_bar(width = 1, stat = "identity", color = "black") +
              coord_polar("y", start = 0) +
              scale_fill_manual(values = colors, guide = "none") +
              ggtitle("A") +
              # labs(fill = "Somatic Gene", x = NULL) +
              theme(panel.background = element_blank(), plot.background = element_blank(),
                    axis.text = element_blank(),
                    axis.ticks = element_blank()) +
              geom_labelpath(data =  df_F1, position = position_stack(vjust = 0.5),
                               aes(x = 1.7, y = n, label = paste0(chromosome_num)),
                               size = 4.5, show.legend = FALSE) 

Pie_F2 <- ggplot(df_F2, aes(x = 1, y = n, fill = as.character(chromosome_num))) +
              geom_bar(width = 1, stat = "identity", color = "black") +
              coord_polar("y", start = 0) +
              scale_fill_manual(values = colors, guide = "none") +
              ggtitle("B") +
              # labs(fill = "Somatic Gene", x = NULL) +
              theme(panel.background = element_blank(), plot.background = element_blank(),
                    axis.text = element_blank(),
                    axis.ticks = element_blank()) +
              geom_labelpath(data =  df_F2, position = position_stack(vjust = 0.5),
                               aes(x = 1.7, y = n, label = paste0(chromosome_num)),
                               size = 4.5, show.legend = FALSE) 

ggpubr::ggarrange(Pie_F1, Pie_F2, nrow = 1)

library(forcats)
df_F1 |>
    # mutate(chromosome_num = fct_reorder(chromosome_num, n)) |>
    ggplot(aes(x = n, y = chromosome_num)) +
    geom_bar(aes(x = 30), stat = "identity", fill = '#e0e0e0') +
    geom_bar(stat = "identity") +
    geom_text(aes(x = n,
                  label = sprintf("%2.1f  ", round(n, 1))
                  ), adj = 0, nudge_x = 1, size = 3) +
    # facet_wrap(~ n < median(n),  scales = 'free_y', ncol = 1) +
    scale_x_continuous(breaks = c(0, 10, 20, 30)) +
    labs(x = 'DEGs', y = '') +
    theme(
        panel.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.y = element_text(hjust = 1, size = rel(1)),
        panel.grid = element_blank()
    )
```
